name: Release

on:
  push:
    tags:
      - 'v*'
env:
  ASSET_NAME: "exechc-ubuntu-x86_64.tar.gz"

jobs:
  release:
    name: Publish binaries
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: false  # The golangci-lint action does its own caching.

      - name: Check go mod tidy
        run: go mod tidy && git diff --exit-code go.mod go.sum

      - name: Build
        run: go build -o exechc ./cmd

      - name: Compress file
        uses: a7ul/tar-action@v1.1.0
        id: compress
        with:
          command: c
          files: |
            ./exechc
          outPath: ${{ env.ASSET_NAME }}

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          file: ${{ env.ASSET_NAME }}
          asset_name: ${{ env.ASSET_NAME }}
          tag: ${{ github.ref }}
          overwrite: true
          body: "Exec hc"
